services:
  mc-server:
    build: ./mc-server
    container_name: mc-server
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "25575:25575/tcp"
    volumes:
      - serverfiles:/usr/src/serverfiles
      - servercache:/servercache
    environment:
      EULA: "TRUE"
      TZ: "Europe/Madrid"

  scp-server:
    build: ./scp-server
    container_name: scp-server
    restart: unless-stopped
    ports:
      - "2222:22/tcp"
    volumes:
      - serverfiles:/serverfiles
      - servercache:/servercache
    environment:
      TZ: "Europe/Madrid"

networks:
  proxy:
    external: true

volumes:
  serverfiles:
  servercache:
